architects:
  - yegor256
  - graur
assets:
  settings.xml: objectionary/secrets#settings.xml
  pubring.gpg: objectionary/secrets#pubring.gpg
  secring.gpg: objectionary/secrets#secring.gpg
install: |
  javac -version
  pdd --file=/dev/null
merge:
  script: |
    mvn clean install -Pqulice --errors -Dstyle.color=never
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}" -Dstyle.color=never
    git commit -am "${tag}"
    mvn clean deploy -Pobjectionary -Psonatype --errors --settings ../settings.xml -Dstyle.color=never
